services:
  web:
    image: jpowerlawapsp:1.0
    environment:
      - gpus=all
    network_mode: "host"
    volumes:
    - /mnt/data/jpowerlaw/matrix.npy:/workspace/matrix.npy
    command: java -jar target/apsp-cpu.jar matrix.npy 9
